name: Docs
on: [push, pull_request, workflow_dispatch, repository_dispatch]
permissions:
    contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme furo numpy pandas
      - name: Get files
        env:
          TOKEN: ${{ secrets.FILE_UPDATE }}
        run: |
          curl -H "Authorization: token ${TOKEN}" https://raw.githubusercontent.com/individual-brain-charting/public_analysis_code/master/ibc_data
      - name: Build tasks.rst
        run: |
          python create_tasks_rst.py
      - name: Sphinx build
        run: |
          sphinx-build -b html docs/source/ docs/build/html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          force_orphan: true
